name: 'ci'

on:
  pull_request:
    branches: ['main']
  merge_group:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

    - name: 'Deploy to Cloud Run'
      run: |-
        echo "hello"
